version: '2.1'

services:
  django-recipe-api:
    image: django-recipe-api
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
